//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HTBackupConsole
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HTBackup : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HTBackup object using the connection string found in the 'HTBackup' section of the application configuration file.
        /// </summary>
        public HTBackup() : base("name=HTBackup", "HTBackup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HTBackup object.
        /// </summary>
        public HTBackup(string connectionString) : base(connectionString, "HTBackup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HTBackup object.
        /// </summary>
        public HTBackup(EntityConnection connection) : base(connection, "HTBackup")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SCHEDULER> SCHEDULERs
        {
            get
            {
                if ((_SCHEDULERs == null))
                {
                    _SCHEDULERs = base.CreateObjectSet<SCHEDULER>("SCHEDULERs");
                }
                return _SCHEDULERs;
            }
        }
        private ObjectSet<SCHEDULER> _SCHEDULERs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SCHEDULERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSCHEDULERs(SCHEDULER sCHEDULER)
        {
            base.AddObject("SCHEDULERs", sCHEDULER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="SCHEDULER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SCHEDULER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SCHEDULER object.
        /// </summary>
        /// <param name="sERVERNAME">Initial value of the SERVERNAME property.</param>
        /// <param name="uSER">Initial value of the USER property.</param>
        /// <param name="pASSWORD">Initial value of the PASSWORD property.</param>
        /// <param name="eSSUSER">Initial value of the ESSUSER property.</param>
        /// <param name="eSSPASSWORD">Initial value of the ESSPASSWORD property.</param>
        public static SCHEDULER CreateSCHEDULER(global::System.String sERVERNAME, global::System.String uSER, global::System.String pASSWORD, global::System.String eSSUSER, global::System.String eSSPASSWORD)
        {
            SCHEDULER sCHEDULER = new SCHEDULER();
            sCHEDULER.SERVERNAME = sERVERNAME;
            sCHEDULER.USER = uSER;
            sCHEDULER.PASSWORD = pASSWORD;
            sCHEDULER.ESSUSER = eSSUSER;
            sCHEDULER.ESSPASSWORD = eSSPASSWORD;
            return sCHEDULER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SERVERNAME
        {
            get
            {
                return _SERVERNAME;
            }
            set
            {
                if (_SERVERNAME != value)
                {
                    OnSERVERNAMEChanging(value);
                    ReportPropertyChanging("SERVERNAME");
                    _SERVERNAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SERVERNAME");
                    OnSERVERNAMEChanged();
                }
            }
        }
        private global::System.String _SERVERNAME;
        partial void OnSERVERNAMEChanging(global::System.String value);
        partial void OnSERVERNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USER
        {
            get
            {
                return _USER;
            }
            set
            {
                OnUSERChanging(value);
                ReportPropertyChanging("USER");
                _USER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USER");
                OnUSERChanged();
            }
        }
        private global::System.String _USER;
        partial void OnUSERChanging(global::System.String value);
        partial void OnUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESSUSER
        {
            get
            {
                return _ESSUSER;
            }
            set
            {
                OnESSUSERChanging(value);
                ReportPropertyChanging("ESSUSER");
                _ESSUSER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESSUSER");
                OnESSUSERChanged();
            }
        }
        private global::System.String _ESSUSER;
        partial void OnESSUSERChanging(global::System.String value);
        partial void OnESSUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESSPASSWORD
        {
            get
            {
                return _ESSPASSWORD;
            }
            set
            {
                OnESSPASSWORDChanging(value);
                ReportPropertyChanging("ESSPASSWORD");
                _ESSPASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESSPASSWORD");
                OnESSPASSWORDChanged();
            }
        }
        private global::System.String _ESSPASSWORD;
        partial void OnESSPASSWORDChanging(global::System.String value);
        partial void OnESSPASSWORDChanged();

        #endregion

    
    }

    #endregion

    
}
